### ISSUE TITLE
Le screencast mentionne encore "javascool-light"

### ISSUE THREAD

**Issue by luidnel-maignan** [FrenchTechLead/robusta#3]

**Comment by FrenchTechLead** [comment]
Will be fixed in next release :)

**Comment by FrenchTechLead** [comment]
![b](https://user-images.githubusercontent.com/10856604/68250722-cf4be600-0021-11ea-97f9-4987cc6d4c14.gif)

**Comment by FrenchTechLead** [comment]
Done.
