### ISSUE TITLE
Robusta semble avoir du mal avec les chemins relatifs

### ISSUE THREAD

**Issue by luidnel-maignan** [FrenchTechLead/robusta#6]
En effet, il y a une jre et un jdk d'installés sur les postes en question.

**Comment by FrenchTechLead** [comment]
Je viens d'ajouter la possibilité de renseigner le path du jdk à utiliser dans les paramètres de l'extension vscode :
[https://github.com/Meshredded/vscode-robusta#extension-settings](https://github.com/Meshredded/vscode-robusta#extension-settings)

**Comment by luidnel-maignan** [comment]
Le problème que je mentionne ne concerne pas vscode-robusta mais bel et bien robusta que j'ai testé en ligne de commande avec un chemin explicite vers le java que je souhaite utiliser. Mais j'ai peut-être mal identifié le probleme. En regardant plus en détail, il produit une exeception FileNotFoundException null\test.jar quand je compile un test.jvs

**Comment by luidnel-maignan** [comment]
Il s'agit plutot d'un problème avec les chemins relatifs

**Comment by FrenchTechLead** [comment]
> Il s'agit plutot d'un problème avec les chemins relatifs

Robusta accepte actuellement les chemins relatifs à `robusta.jar` , Ex : dans le cas où on a une arborescence du genre  : 
```
dir .
    |--- robusta.jar
    |--- test.jvs
```
La commande `java -jar robusta.jar compile test.jvs` fonctionne bien.
