### ISSUE TITLE
Les fonctions read* créent de nouvelles fenêtres

### ISSUE THREAD

**Issue by luidnel-maignan** [FrenchTechLead/robusta#8]
Observé avec le code minimal suivant sur ma machine sous Windows 10:
void main() {
	while(true) {
		readInt("");
	}
}

**Comment by FrenchTechLead** [comment]
Quel est le comportement attendu pour un readInt ?

**Comment by luidnel-maignan** [comment]
Je dois préciser que ce sont des nouvelles fenêtres de consoles qui
s'affichent. Donc après 10 readInt, il y a 10 frames "console".

Le jeu. 5 déc. 2019 à 19:31, MECHERI Akram <notifications@github.com> a
écrit :

**Comment by FrenchTechLead** [comment]
D'accord Bien vu ;)
Je viens de corriger
